services:
  traefik:
    image: station-test
    container_name: station-test
    hostname: 'station'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/station/work:/work
      - /app:/app
    networks:
      - traefik

networks:
  proxy:
    external:
      name: traefik

