FROM zzci/station

WORKDIR /app

ENV PATH=/root/.cargo/bin:/usr/local/go/bin:/root/go/bin:$PATH

RUN \
    ## nodejs
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -; \
    #
    ## apt update.
    apt-get -y update; apt-get -y upgrade;\
    #
    ## nodejs
    apt-get install -y make pkg-config nodejs gcc g++; \
    #
    ## config node
    corepack enable; \
    #
    ## rust
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path; \
    echo 'source "$HOME/.cargo/env"' >> ~/.zshrc; \
    #
    ## golang
    wget -qO "/tmp/go.tar.gz" https://go.dev/dl/go1.19.linux-amd64.tar.gz; \
    rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go.tar.gz; \
    #
    ## clear
    apt-get autoclean -y; apt-get autoremove -y; rm -rf /var/lib/apt/lists/*; rm -rf /tmp/*; rm -rf /root/.cache; \
    #
    ## pack /root
    mkdir -p /build/res/; \
    rm -rf /build/res/root.tar.gz; \
    tar -czf /build/res/root.tar.gz /root; \
    rm -rf /root; mkdir -p /root
