FROM zzci/station

WORKDIR /app

ENV PATH=/usr/local/go/bin:/root/go/bin:$PATH

RUN \
    ## nodejs
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -; \
    #
    ## apt update.
    apt-get -y update; apt-get -y upgrade; \
    #
    ## golang
    add-apt-repository ppa:longsleep/golang-backports; \
    #
    ## nodejs
    apt-get install -y make pkg-config nodejs gcc golang-go g++; \
    #
    ## config node
    corepack enable; \
    #
    ## clear
    apt-get autoclean -y; apt-get autoremove -y; rm -rf /var/lib/apt/lists/*; rm -rf /tmp/*; rm -rf /root/.cache; \
    #
    ## pack /root
    mkdir -p /build/res/; \
    rm -rf /build/res/root.tar.gz; \
    tar -czf /build/res/root.tar.gz /root; \
    rm -rf /root; mkdir -p /root
