name: build-push-dev

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build-push-station"]
    types: [completed]
    branches: [main]

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/build.yml
    with:
      image: zzci/dev
      dockerfile: Dockerfile.dev
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
