name: build-push-station

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 1 3,6,9,12 *'
env:
  IMAGE_NAME: zzci/station

jobs:
  push:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build docker tag
        id: tag
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          Build="$IMAGE_NAME:$VERSION"

          Date=`date "+%Y%m%d"`
          Date="$IMAGE_NAME:$Date"

          echo "tag-date=$Date" >> $GITHUB_ENV
          echo "tag-build=$Build" >> $GITHUB_ENV

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ env.tag-date }}
            ${{ env.tag-build }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
